//! Visual UI Designer for Squeezer.
//! Allows dragging widgets and connecting them to VPL parameters.

use limestudio_surface::model::stable_id::SurfaceId as Id;
use limestudio_surface::ui_ir::{DisplaySignal, FrameStyle, SurfaceWidget};

pub struct Designer {
    pub widgets: Vec<DesignerWidget>,
    pub selected_id: Option<Id>,
    pub is_dragging: bool,
    pub available_params: Vec<String>,
}

pub struct DesignerWidget {
    pub id: Id,
    pub kind: WidgetKind,
    pub pos: [f32; 2],
    pub label: String,
    pub param_id: Option<String>,
}

pub enum WidgetKind {
    Knob,
    Slider,
    Button,
    Label,
}

impl Default for Designer {
    fn default() -> Self {
        Self::new()
    }
}
impl Designer {
    pub fn new() -> Self {
        let mut d = Self {
            widgets: Vec::new(),
            selected_id: None,
            is_dragging: false,
            available_params: vec![
                "cutoff".to_string(),
                "resonance".to_string(),
                "gain".to_string(),
            ],
        };
        d.add_widget(WidgetKind::Knob, [200.0, 200.0]);
        d.add_widget(WidgetKind::Button, [300.0, 200.0]);
        d
    }

    pub fn handle_event(&mut self, event: &limestudio_surface::runtime::input::SurfaceEvent) {
        use limestudio_surface::runtime::input::SurfaceEvent::*;
        match event {
            PointerDown { position, .. } => {
                // Hit test
                self.selected_id = self
                    .widgets
                    .iter()
                    .find(|w| w.hit_test(*position))
                    .map(|w| w.id);

                if self.selected_id.is_some() {
                    self.is_dragging = true;
                }
            }
            PointerMove { position, .. } => {
                if self.is_dragging {
                    if let Some(id) = self.selected_id {
                        if let Some(w) = self.widgets.iter_mut().find(|w| w.id == id) {
                            w.pos = [position.x, position.y];
                        }
                    }
                }
            }
            PointerUp { .. } => {
                self.is_dragging = false;
            }
            _ => {}
        }
    }

    pub fn build_ui(&self) -> SurfaceWidget {
        use limestudio_surface::ui_ir::SurfaceWidget::*;

        let canvas = Box {
            style: FrameStyle::Standard,
            children: self.widgets.iter().map(|w| w.to_widget()).collect(),
        };

        let param_list = Box {
            style: FrameStyle::Message,
            children: self
                .available_params
                .iter()
                .map(|p| SurfaceWidget::Button {
                    id: Id::from_seed(p),
                    label: format!("BIND: {}", p),
                    is_active: false,
                })
                .collect(),
        };

        limestudio_surface::ui_ir::SurfaceWidget::Row {
            children: vec![param_list, canvas],
        }
    }

    pub fn bind_param(&mut self, widget_id: Id, param_id: String) {
        if let Some(w) = self.widgets.iter_mut().find(|w| w.id == widget_id) {
            w.param_id = Some(param_id);
            w.label = w.param_id.clone().unwrap().to_uppercase();
        }
    }

    pub fn add_widget(&mut self, kind: WidgetKind, pos: [f32; 2]) {
        let id = Id::generate();
        self.widgets.push(DesignerWidget {
            id,
            kind,
            pos,
            label: "New Widget".to_string(),
            param_id: None,
        });
    }

    /// Generate the Rust code (view! macro) from the current layout.
    /// This follows the "The Law of 8px" and HIG v3.0 standards.
    pub fn generate_code(&self) -> String {
        let mut code = String::from("// Automatically generated by Squeezer Visual Designer\n");
        code.push_str("view! {\n    vbox![\n        Label::new(\"GENERATED UI\").secondary(),\n        hbox![\n");

        for w in &self.widgets {
            let param = w.param_id.as_deref().unwrap_or("unbound");
            let line = match w.kind {
                WidgetKind::Knob => format!(
                    "            Knob::new(params.{}).label(\"{}\"),\n",
                    param, w.label
                ),
                WidgetKind::Slider => format!(
                    "            Slider::new(params.{}).label(\"{}\"),\n",
                    param, w.label
                ),
                WidgetKind::Button => format!(
                    "            Toggle::new(params.{}).label(\"{}\"),\n",
                    param, w.label
                ),
                WidgetKind::Label => format!("            Label::new(\"{}\"),\n", w.label),
            };
            code.push_str(&line);
        }

        code.push_str("        ]\n    ]\n}");
        code
    }
}

impl DesignerWidget {
    fn hit_test(&self, cursor: glam::Vec2) -> bool {
        let dx = cursor.x - self.pos[0];
        let dy = cursor.y - self.pos[1];
        // 40px radius hit area for simplicity
        (dx * dx + dy * dy) < 1600.0
    }

    fn to_widget(&self) -> SurfaceWidget {
        match self.kind {
            WidgetKind::Knob => SurfaceWidget::Knob {
                id: self.id,
                label: self.label.clone(),
                signal: DisplaySignal::Linear(0.0),
            },
            WidgetKind::Button => SurfaceWidget::Button {
                id: self.id,
                label: self.label.clone(),
                is_active: false,
            },
            _ => SurfaceWidget::Label {
                text: self.label.clone(),
                is_secondary: false,
            },
        }
    }
}
