//! "Always Show Rust" — IR → Rust コード生成
//!
//! VPLで組んだら常にRust equivalentが表示される。
//! 学習、信頼性、exportability、escape hatch — 全部解決。
//! これがあると「玩具」から脱出できる。

use crate::ir::IrOp;
use crate::compile::CompiledGraph;

/// CompiledGraphをRustコードに変換
pub fn ir_to_rust(program: &CompiledGraph) -> String {
    let mut out = String::new();
    let mut indent = 1;
    let tab = "    ";

    out.push_str("/// Auto-generated by LimeStudio VPL\n");
    out.push_str("/// This is the Rust equivalent of your visual graph.\n");
    out.push_str("fn process_sample(\n");
    out.push_str("    input_l: f32,\n");
    out.push_str("    input_r: f32,\n");
    out.push_str("    params: &[f32],\n");
    out.push_str("    sample_rate: f32,\n");
    out.push_str(") -> (f32, f32) {\n");

    // Buffer declarations
    if program.buffer_count > 0 {
        out.push_str(&format!(
            "{}let mut buf = [0.0f32; {}];\n",
            tab.repeat(indent),
            program.buffer_count
        ));
    }

    out.push_str(&format!("{}let mut stack = Vec::<f32>::new();\n", tab.repeat(indent)));
    out.push_str(&format!("{}let (mut out_l, mut out_r) = (0.0f32, 0.0f32);\n\n", tab.repeat(indent)));

    // Generate ops
    for (i, op) in program.ops.iter().enumerate() {
        let line = match op {
            IrOp::LoadConst(v) => format!("stack.push({:.6});", v),
            IrOp::LoadParam(id) => format!("stack.push(params[{}]);", id.0),
            IrOp::LoadBuffer(id) => format!("stack.push(buf[{}]);", id.0),
            IrOp::StoreBuffer(id) => format!("buf[{}] = *stack.last().unwrap();", id.0),
            IrOp::Add => {
                "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(a + b); }".into()
            }
            IrOp::Mul => {
                "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(a * b); }".into()
            }
            IrOp::MulConst(v) => {
                format!("{{ let a = stack.pop().unwrap(); stack.push(a * {:.6}); }}", v)
            }
            IrOp::AddConst(v) => {
                format!("{{ let a = stack.pop().unwrap(); stack.push(a + {:.6}); }}", v)
            }
            IrOp::Sub => {
                "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(a - b); }".into()
            }
            IrOp::Div => {
                "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(if b != 0.0 { a / b } else { 0.0 }); }".into()
            }
            IrOp::Clamp { min, max } => {
                format!("{{ let v = stack.pop().unwrap(); stack.push(v.clamp({:.6}, {:.6})); }}", min, max)
            }
            IrOp::Abs => "{ let v = stack.pop().unwrap(); stack.push(v.abs()); }".into(),
            IrOp::Sqrt => "{ let v = stack.pop().unwrap(); stack.push(v.sqrt()); }".into(),
            IrOp::Neg => "{ let v = stack.pop().unwrap(); stack.push(-v); }".into(),
            IrOp::Sin => "{ let v = stack.pop().unwrap(); stack.push(v.sin()); }".into(),
            IrOp::Cos => "{ let v = stack.pop().unwrap(); stack.push(v.cos()); }".into(),
            IrOp::LoadSampleRate => "stack.push(sample_rate);".into(),
            IrOp::Delay { samples, state_id } => {
                format!("// Delay: {} samples (state slot {})", samples, state_id.0)
            }
            IrOp::ReadInput { channel } => {
                match channel {
                    0 => "stack.push(input_l);".into(),
                    1 => "stack.push(input_r);".into(),
                    _ => format!("stack.push(0.0); // input ch{}", channel),
                }
            }
            IrOp::WriteOutput { channel } => {
                match channel {
                    0 => "out_l = stack.pop().unwrap();".into(),
                    1 => "out_r = stack.pop().unwrap();".into(),
                    _ => format!("let _ = stack.pop(); // output ch{}", channel),
                }
            }
            IrOp::CopyBuffer(src, dst) => format!("buf[{}] = buf[{}];", dst.0, src.0),
            IrOp::AddBuffer(src, dst) => format!("buf[{}] += buf[{}];", dst.0, src.0),
        };

        out.push_str(&format!("{}{} // op[{}]\n", tab.repeat(indent), line, i));
    }

    out.push_str(&format!("\n{}(out_l, out_r)\n", tab.repeat(indent)));
    out.push_str("}\n");

    out
}

/// 高レベルRust表現への変換（スタック操作を変数名に展開）
/// よりFabFilter的な「読めるコード」を生成する
pub fn ir_to_readable_rust(program: &CompiledGraph) -> String {
    let mut out = String::new();
    let mut var_counter: u32 = 0;
    let mut stack: Vec<String> = Vec::new();

    out.push_str("/// Auto-generated by LimeStudio VPL (readable)\n");
    out.push_str("fn process(input_l: f32, input_r: f32, params: &[f32], sr: f32) -> (f32, f32) {\n");

    let mut out_l = String::from("0.0");
    let mut out_r = String::from("0.0");

    for op in &program.ops {
        match op {
            IrOp::ReadInput { channel } => {
                let name = match channel {
                    0 => "input_l".to_string(),
                    1 => "input_r".to_string(),
                    _ => "0.0".to_string(),
                };
                stack.push(name);
            }
            IrOp::LoadConst(v) => {
                stack.push(format!("{:.4}", v));
            }
            IrOp::LoadParam(id) => {
                stack.push(format!("params[{}]", id.0));
            }
            IrOp::LoadBuffer(id) => {
                stack.push(format!("buf_{}", id.0));
            }
            IrOp::LoadSampleRate => {
                stack.push("sr".to_string());
            }
            IrOp::MulConst(v) => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {} * {:.4};\n", var, a, v));
                stack.push(var);
            }
            IrOp::AddConst(v) => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {} + {:.4};\n", var, a, v));
                stack.push(var);
            }
            IrOp::Mul => {
                let b = stack.pop().unwrap_or_else(|| "?".into());
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {} * {};\n", var, a, b));
                stack.push(var);
            }
            IrOp::Add => {
                let b = stack.pop().unwrap_or_else(|| "?".into());
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {} + {};\n", var, a, b));
                stack.push(var);
            }
            IrOp::Sub => {
                let b = stack.pop().unwrap_or_else(|| "?".into());
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {} - {};\n", var, a, b));
                stack.push(var);
            }
            IrOp::Div => {
                let b = stack.pop().unwrap_or_else(|| "?".into());
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = if {} != 0.0 {{ {} / {} }} else {{ 0.0 }};\n", var, b, a, b));
                stack.push(var);
            }
            IrOp::Sin => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {}.sin();\n", var, a));
                stack.push(var);
            }
            IrOp::Cos => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {}.cos();\n", var, a));
                stack.push(var);
            }
            IrOp::Abs => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {}.abs();\n", var, a));
                stack.push(var);
            }
            IrOp::Sqrt => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {}.sqrt();\n", var, a));
                stack.push(var);
            }
            IrOp::Neg => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = -{};\n", var, a));
                stack.push(var);
            }
            IrOp::Clamp { min, max } => {
                let a = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("v{}", var_counter);
                var_counter += 1;
                out.push_str(&format!("    let {} = {}.clamp({:.4}, {:.4});\n", var, a, min, max));
                stack.push(var);
            }
            IrOp::StoreBuffer(id) => {
                let val = stack.last().cloned().unwrap_or_else(|| "?".into());
                out.push_str(&format!("    let buf_{} = {};\n", id.0, val));
            }
            IrOp::WriteOutput { channel } => {
                let val = stack.pop().unwrap_or_else(|| "0.0".into());
                match channel {
                    0 => out_l = val,
                    1 => out_r = val,
                    _ => {}
                }
            }
            IrOp::CopyBuffer(src, dst) => {
                out.push_str(&format!("    let buf_{} = buf_{};\n", dst.0, src.0));
            }
            IrOp::AddBuffer(src, dst) => {
                out.push_str(&format!("    let buf_{0} = buf_{0} + buf_{1};\n", dst.0, src.0));
            }
            IrOp::Delay { samples, state_id } => {
                let input_val = stack.pop().unwrap_or_else(|| "?".into());
                let var = format!("delayed_{}", state_id.0);
                out.push_str(&format!("    let {} = delay({}, {} /* samples */); // state[{}]\n",
                    var, input_val, samples, state_id.0));
                stack.push(var);
            }
        }
    }

    out.push_str(&format!("\n    ({}, {})\n", out_l, out_r));
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;
    use crate::compile::CompiledGraph;

    #[test]
    fn test_simple_gain_codegen() {
        let program = CompiledGraph {
            ops: vec![
                IrOp::ReadInput { channel: 0 },
                IrOp::MulConst(0.5),
                IrOp::WriteOutput { channel: 0 },
            ],
            buffer_count: 0,
            state_count: 0,
        };

        let rust = ir_to_rust(&program);
        assert!(rust.contains("input_l"));
        assert!(rust.contains("0.5"));
        assert!(rust.contains("out_l"));
    }

    #[test]
    fn test_readable_gain() {
        let program = CompiledGraph {
            ops: vec![
                IrOp::ReadInput { channel: 0 },
                IrOp::MulConst(0.7),
                IrOp::WriteOutput { channel: 0 },
            ],
            buffer_count: 0,
            state_count: 0,
        };

        let rust = ir_to_readable_rust(&program);
        assert!(rust.contains("input_l * 0.7000"));
        assert!(rust.contains("fn process"));
    }

    #[test]
    fn test_complex_graph_codegen() {
        // Input -> Gain(0.5) -> Mix with Osc -> Output
        let program = CompiledGraph {
            ops: vec![
                IrOp::ReadInput { channel: 0 },
                IrOp::StoreBuffer(BufferId(0)),
                IrOp::LoadBuffer(BufferId(0)),
                IrOp::MulConst(0.5),
                IrOp::LoadConst(440.0),
                IrOp::LoadSampleRate,
                IrOp::Div,
                IrOp::Sin,
                IrOp::Add,
                IrOp::WriteOutput { channel: 0 },
            ],
            buffer_count: 1,
            state_count: 0,
        };

        let rust = ir_to_readable_rust(&program);
        // Should produce readable variable chain
        assert!(rust.contains("sin()"));
        assert!(rust.contains("440.0"));
    }
}
